name: Build and deploy Node.js app to Azure Web App - omniplex-rahul

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'  # ✅ Enable npm caching


      - name: Install all dependencies (including dev)
        run: npm ci  # ← Changed: Install ALL dependencies for build

      - name: Build application
        run: npm run build

      - name: Install production dependencies only
        run: |
          rm -rf node_modules
          npm ci --only=production  # ← Clean production install for deployment

      - name: Create deployment package
        run: |
          # Create a clean deployment structure
          mkdir deployment-package
          
          # Copy built application
          cp -r .next deployment-package/
          cp -r public deployment-package/
          cp package.json deployment-package/
          cp package-lock.json deployment-package/
          cp -r node_modules deployment-package/
          
          # Create startup script for Azure
          echo '#!/bin/sh' > deployment-package/startup.sh
          echo 'cd /home/site/wwwroot' >> deployment-package/startup.sh
          echo 'npm start' >> deployment-package/startup.sh
          chmod +x deployment-package/startup.sh
          
          cd deployment-package
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1  # ✅ Cleanup artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC4E676092A64BD4BBF5A938EB243A3A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75A18EF9AB404E82BB84BC240C604A3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C930389CCD104DE480949012285039CD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omniplex-rahul'
          slot-name: 'Production'
          package: .
